# Generated by Django 3.2 on 2023-11-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_employee_hire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_id', models.IntegerField(default=0)),
                ('client_email', models.EmailField(blank=True, max_length=255)),
                ('client_phone', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('cl_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.client')),
            ],
        ),
    ]
