# Generated by Django 3.2 on 2023-12-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_client_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cl_name',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='joining_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
