# Generated by Django 3.2 on 2023-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_auto_20231202_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='project_details',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
