# Generated by Django 3.2 on 2023-12-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_auto_20231202_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
