# Generated by Django 3.2 on 2023-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
