# Generated by Django 3.2 on 2023-12-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0011_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
